[graph]
all-features = true

[advisories]
ignore = []

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
]
confidence-threshold = 0.93
exceptions = []

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-workspace = true
allow = [
    "itoa@1.0.18",
    "memchr@2.8.3",
    "proc-macro2@1.0.107",
    "quote@1.0.47",
    "serde@1.0.229",
    "serde_core@1.0.229",
    "serde_derive@1.0.229",
    "serde_json@1.0.151",
    "syn@3.0.3",
    "unicode-ident@1.0.24",
    "zmij@1.0.23",
]
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []