[package]
name = "ntsql-storage-file"
version = "0.1.0"
description = "Versioned filesystem commit log for ntsql transactions"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
ntsql-page.workspace = true
ntsql-transaction.workspace = true
ntsql-wal.workspace = true

[lints]
workspace = true
